# Generated by Django 4.1.5 on 2023-01-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_remove_post_dislike"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="deleted",),
    ]
