# Generated by Django 4.1.5 on 2023-01-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remove_comment_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
