# Generated by Django 4.1.5 on 2023-01-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_post_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likeHeart",
            field=models.TextField(
                default='<i class="fa-solid fa-heart" style="color:red"></i>'
            ),
        ),
        migrations.AlterField(
            model_name="post", name="like", field=models.BooleanField(default=False),
        ),
    ]
