# Generated by Django 4.1.5 on 2023-01-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_alter_post_likeheart"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="likeHeart",),
    ]
